<?php
/**
 *
 * @category  Sailthru
 * @package   Sailthru_Email
 * @author    Kwadwo Juantuah <support@sailthru.com>
 */

?>

<?php if (!Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
<?php   
        //$domain = Mage::getStoreConfig('sailthru/horizon/horizon_domain');
        $domain = Mage::helper('sailthruemail')->getHorizonDomain();
        $concierge = Mage::helper('sailthruemail')->isConciergeEnabled() ? ", concierge: { from: 'top', threshold: 400}" : '';
        //$concierge = Mage::getStoreConfig(Sailthru_Email_Helper_Data::XML_PATH_CONCIERGE_ENABLED) ? ', concierge: { from: "top", threshold: 10}' : 'not true';
?>
<!--BEGIN SAILTHRU HORIZON & CONCIERGE -->
<script type="text/javascript">
//<![CDATA[
    (function() {
        function loadHorizon() {
            var s = document.createElement('script');
            s.type = 'text/javascript';
            s.async = true;
            s.src = location.protocol + '//ak.sail-horizon.com/horizon/v1.js';
            var x = document.getElementsByTagName('script')[0];
            x.parentNode.insertBefore(s, x);
        }
        loadHorizon();
        var oldOnLoad = window.onload;
        window.onload = function() {
            if (typeof oldOnLoad === 'function') {
                oldOnLoad();
            }
            Sailthru.setup({
                domain: '<?php echo Mage::helper('sailthruemail')->getHorizonDomain()?>' <?php echo "$concierge"; ?>
            });
        };
    })();
//]]>
</script>
<!-- END SAILTHRU HORIZON & CONCIERGE -->

<!--BEGIN SAILTHRU TAGS-->
<?php $product = Mage::registry('current_product'); ?>
<meta name="sailthru.title" content="<?php echo htmlspecialchars($product->getName()); ?>" />
<meta name="sailthru.tags" content="<?php echo htmlspecialchars($product->getMetaKeyword()); ?>" />
<meta name="sailthru.description" content="<?php echo htmlspecialchars($product->getDescription()); ?>" />
<meta name="sailthru.image.full" content="<?php echo htmlspecialchars($product->getImageUrl()); ?>" />
<meta name="sailthru.image.thumb" content="<?php echo htmlspecialchars($product->getThumbnailUrl(50, 50)); ?>" />
<meta name="sailthru.price" content="<?php echo htmlspecialchars($product->getPrice()*100); ?>" />
<!--END SAILTHRU TAGS-->

<?php endif; ?>
